version: '3'

services:

   discovery:
     image: manolo/discovery-server
     ports:
      - "8761:8761"

   configserver:
     image: manolo/config-server
     ports:
      - "8888:8888"
     links:
      - discovery

   gateway:
     image: manolo/api-gateway
     entrypoint: ["./wait-for-it.sh","configserver:8888","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
     ports:
      - "9000:9000"
     links:
      - discovery
      - configserver
     restart: on-failure
   
   myvault:
     image: vault
     ports:
      - "8200:8200"
     volumes:
      - ./vault/file:/vault/file:rw
      - ./vault/config:/vault/config:rw
     cap_add:
      - IPC_LOCK
     entrypoint: vault server -config=/vault/config/vault.json
     
   tracing-server:
     image: openzipkin/zipkin
     ports:
      - "9411:9411"
        