version: '3'

services:

   discovery:
     image: manolo/discovery-server
     ports:
      - "8761:8761"

   configserver:
     image: manolo/config-server
     ports:
      - "8888:8888"
     links:
      - discovery

   gateway:
     image: manolo/api-gateway
     ports:
      - "9000:9000"
     links:
      - discovery
      - configserver
     restart: on-failure
      