server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configurations/
  security:
    user:
      name: my-username
      password: my-password

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
      
  